# Generated by Django 3.1.4 on 2020-12-16 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('discountPercentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('cost', models.IntegerField(default=0)),
                ('days', models.IntegerField(default=0)),
                ('package', models.CharField(max_length=100)),
                ('rating', models.FloatField(default='1')),
                ('image', models.TextField(default='Canada-Montreal')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
    ]
